### ISSUE TITLE
1.3.2 Crashes multiple devices

### ISSUE THREAD

**Issue by gerbil-snot** [peterprd/libpddokdo#11]
After upgrading, no issues can be seen immediately. Took me a few hours to encounter issues; Safari kept crashing for me repeatedly. I rebooted the user space and got hung up on the Apple logo, hard reset, tried to rejailbreak, same thing. Had to turn off load tweaks and downgrade the tweak to get everything working again. 

Device info probably doesn't matter but I'll provide it anyway: iPhone 12 Pro Max iOS 14.3 unc0ver Fugu jailbreak. 

The Reddit post with more affected users can be found here: https://reddit.com/r/jailbreak/comments/v0ssbi/discussion_libpddokdo_causing_issues_when/

**Comment by s8ngyu** [comment]
Hopefully 00253e4 fixes both respring loop and .DS_Store issue.

Since I cannot leave a comment on Reddit, It would be really nice for anyone to deliver my message. It was my mistake, I should've checked the final builds multiple times. Version 1.3.2 which caused respring loop has been hidden from Havoc now, and I just submitted 1.3.3. I am really sorry for the inconvenience.

**Comment by PoomSmart** [comment]
@s8ngyu I suspect that your lib was compiled with iOS 15.5 minimum OS and that's when undefined crashing happens on most devices.

**Comment by PoomSmart** [comment]
Just saw version 1.3.4, yes it's in the right track but I'm sure you can do latest:11.4 too?

**Comment by s8ngyu** [comment]
> Just saw version 1.3.4, yes it's in the right track but I'm sure you can do latest:11.4 too?

I'll do that when I get home. Thank you.
